version: "3.9"

services:
  # -------------------------
  # ELK
  # -------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false  # re-enable in production
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  # -------------------------
  # MICROSERVICES
  # -------------------------
  data-upload:
    build:
      context: ./services/data-upload
    container_name: data-upload
    depends_on:
      - elasticsearch
    environment:
      - STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
      - STORAGE_ACCOUNT_KEY=${STORAGE_ACCOUNT_KEY}
      - CONTAINER_NAME=${CONTAINER_NAME}
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200
    ports:
      - "8001:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  data-query:
    build:
      context: ./services/data-query
    container_name: data-query
    depends_on:
      - elasticsearch
    environment:
      - STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
      - STORAGE_ACCOUNT_KEY=${STORAGE_ACCOUNT_KEY}
      - CONTAINER_NAME=${CONTAINER_NAME}
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200
    ports:
      - "8002:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
